name: GitHub Actions Demo
on: [push]
jobs:
  testing-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: testing first run
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

    - name: print files
      run: ls -ltrh
    - name: print path
      run: pwd | ls -ltrha

    - name: checking out code
      uses: actions/checkout@v4

    - name: now check path
      run: ls -ltrha

    - name: pass multiple commands in one go
      run: |
          echo "hello world"
          printenv
          echo $PATH
          history
          touch new.txt
  New-jobs:
    runs-on: ubunutu-latest
    needs: [testing-jobs]
    steps:
    - name: what does needs do it will wait for the first testing-jobs to be completed you can add multiple dependency
      run: |
          echo "printing"
          ls -ltrh
          echo "a"




      
