name: GitHub Actions Demo

on:
  workflow_dispatch: {}           # manual/API trigger
  push:
    branches: [main, develop,'!feature/**']
  # schedule:
  #   - cron: "*/5 * * * *"       # GitHub cron min practical interval ~5 min

env:
  N_VAR: access
  # Never dump secrets/contexts to logs
  # CHECK_SEC: ${{ toJson(secrets) }}
  # GIT_CHK:  ${{ toJson(github) }}


jobs:
  testing-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: testing first run
        run: echo "🎉 Triggered by a ${{ github.event_name }} event."

      - name: print files (workspace before checkout)
        run: ls -ltrh

      - name: print path (don't pipe pwd into ls)
        run: |
          pwd
          ls -ltrha

      - name: checking out code
        uses: actions/checkout@v4

      - name: now check path (after checkout)
        run: ls -ltrha

      - name: pass multiple commands in one go
        env:
          TT_VAR: ${{ vars.TT_VAR }}
        run: |
          echo "hello world"
          printenv | sort
          echo "$PATH"
          touch new.txt
          echo "${{ env.N_VAR }}"
          # Never print secrets:
          # echo "${{ secrets.REPO_PASS }}"
          echo "$TT_VAR"

  New-jobs:
    if: github.repository_owner == 'Muhammadowais-ops'
    runs-on: ubuntu-latest
    needs: [testing-jobs]
    concurrency:
      group: to-remove-job
      cancel-in-progress: true
    steps:
      - name: needs explanation
        run: |
          echo "This waits for testing-jobs to finish"
          ls -ltrh

      - name: create an artifact file
        run: |
          echo "hello" > new.txt
          mkdir -p /opt/td/
          mv new.txt /opt/td/

      - name: upload artifact (kept 5 days)
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /opt/td/new.txt
          retention-days: 5

  New-jobs2:
    runs-on: ubuntu-latest
    needs: [New-jobs]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: check downloaded artifact
        run: ls -ltrh

      # ⚠️ Cross-repo trigger using PAT secret: DOWNSTREAM_PAT
      - name: Trigger downstream workflow (cross-repo)
        env:
          GH: ${{ secrets.DOWNSTREAM_PAT }}   # PAT with Actions: write + Contents: read on TARGET repo
        run: |
          echo "$GH" | gh auth login --hostname github.com --with-token
          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Muhammadowais-ops/github-actions-test-java/actions/workflows/github-actions.yaml/dispatches \
            -f ref=master

          # If TARGET_WORKFLOW is a file, ensure it's the exact filename, e.g. `github-actions.yml`.
          # Or switch to numeric workflow ID for reliability.

  Testing-envirnoment:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "Hello World"
      T_VAR: "Testing var"
    steps:
      - name: Print variable - job-level env
        timeout-minutes: 2
        run: echo "$MY_VAR"

      - name: Step with its own env
        env:
          STEP_VAR: "Step Value"
        run: echo "$STEP_VAR"

      - name: Access job-level var in any step (fixed)
        run: |
          echo "$T_VAR"
          # this is the content you can check it
