name: GitHub Actions Demo
on: [push]
jobs:
  testing-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: testing first run
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

    - name: print files
      run: ls -ltrh
    - name: print path
      run: pwd | ls -ltrha

    - name: checking out code
      uses: actions/checkout@v4

    - name: now check path
      run: ls -ltrha

    - name: pass multiple commands in one go
      run: |
          echo "hello world"
          printenv
          echo $PATH
          history
          touch new.txt
  New-jobs:
    runs-on: ubuntu-latest
    needs: [testing-jobs]
    steps:
    - name: what does needs do it will wait for the first testing-jobs to be completed you can add multiple dependency
      run: |
          echo "printing"
          ls -ltrh
    - name: testing artifact upload
      run: |
          echo "hello" >> new.txt
          mkdir -p /opt/td/
          mv new.txt /opt/td
    - name: we are using upload artifact and set it rentention period for 5 days default is more than that artificact      
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /opt/td/new.txt
        retention-days: 5

  New-jobs2:
    runs-on: ubuntu-latest
    needs: [New-jobs]
    steps:
    - name: now i am downloading the artifact from upload artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: now i am checking it download artifact
      run: |
          ls -ltrh  






      
